import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {AuthProvider} from './context/AuthContext';
import { Toaster } from "sonner";
import { ThemeProvider } from "next-themes";
import { UserProvider } from "@/context/userContext";
import {GoogleOAuthProvider} from "@react-oauth/google"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID!}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <AuthProvider>
              <UserProvider>{children}</UserProvider>
            </AuthProvider>
          </ThemeProvider>
        </GoogleOAuthProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
